name: "publish"
on:
  push:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: pnpm install
      #- run: cargo install tauri-cli --git https://github.com/tauri-apps/tauri --debug
      #- name: install app dependencies
      #  run: cd zactualproject && pnpm install
      #- run: cargo check
      #  working-directory: tauri-project/src-tauri/
      #- run: |
      #    npm install -g @tauri-apps/cli
      #    tauri init --ci --app-name tauri-project
      #- run: cargo install tauri-cli --debug --git https://github.com/tauri-apps/tauri --branch fix/zip-deflate
      - uses: tauri-apps/tauri-action@fix/561
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          includeDebug: true
          includeRelease: false
          prerelease: false
          distPath: ../dist
          bundleIdentifier: com.fl.test
          appName: ../package.json
          appVersion: ../package.json
          #includeUpdaterJson: true
          #updaterJsonPreferNsis: false
          #updaterJsonKeepUniversal: false
          #projectPath: zactualproject
          #tauriScript: cargo tauri
